/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SpaceAdventures__factory } from "./SpaceAdventures__factory";
export { SpaceCoins__factory } from "./SpaceCoins__factory";
export { SpaceShips__factory } from "./SpaceShips__factory";
